name: flightdata
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyopensky
  - geopandas
  - cartopy
  - geodatasets
  - geopy
  - matplotlib
  - contextily
  - shapely
  - earthaccess
  - netCDF4
  - h5netcdf
  - bottleneck